# MATERIALS: item names can be found in here. THEY ARE CASE SENSITIVE
#  https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Material.html


# Items the player SHOULD NOT drop
DropBlacklist:
  - "SPRUCE_LOG"